### ISSUE TITLE
L-39, radio volume dials out of range

### ISSUE THREAD

**Issue by jdahlblom** [DCS-Skunkworks/dcs-bios#394]
```
FRONT_RADIO_VOL
BACK_RADIO_VOL
FRONT_SPU_VOL
BACK_SPU_VOL
```
When mission starts the values for these dials (argument value) is 1. 
Once they are moved their value falls within the limit ```{ 0.0, 0.8 }``` and never goes to 1 again. One or more errors will be reported in the log until they all are moved once.

```
2023-10-09 18:59:40  ERROR  Util.lua: value 81918.000000 is too large for address 13240 mask 65535
2023-10-09 18:59:40  ERROR  Util.lua: value 81918.000000 is too large for address 13234 mask 65535
2023-10-09 18:59:40  ERROR  Util.lua: value 81918.000000 is too large for address 13236 mask 65535
2023-10-09 18:59:40  ERROR  Util.lua: value 81918.000000 is too large for address 13238 mask 65535
```

**Comment by charliefoxtwo** [comment]
This seems like the default value for these controls is, for some reason, `1`. But of course the actual range for these controls defined in the dcs luas (as you've noticed) is `{ 0, 0.8 }`.

This doesn't really make a lot of sense to me since as far as I can tell in the luas the default is `0.5` and I can't see anywhere it's set to one, but I've experienced this with other modules as well. I'm not sure there's much we can do here.

**Comment by jdahlblom** [comment]
Yeah, I had to jog my memory and did a new test with insight. It is 1 when mission starts, move the dials and they fall withing the 0-0.8 range. Wanted to test with the new version.

**Comment by charliefoxtwo** [comment]
The model supports values up to 1, but they are clamped to 0.8 in the luas, so any value outside of 0.8 is a bug in DCS. Closing.
