### ISSUE TITLE
F15E: UFC key 7 and 0 names incompatible from 2.8.7 to Beta

### ISSUE THREAD

**Issue by atcz** [DCS-Skunkworks/dcs-bios#523]
**DCS-BIOS version**
DCS-BIOS_0.7.49.zip

**DCS-BIOS Control**
UFC Keys 7 and 0

**Describe the bug**
Testing the open beta download, my code for UFC keys 0 and 7 no longer works.  The key names were changed to remove an underscore.

v0.7.49
definePushButton("F_UFC_KEY__7", 56, 3030, 299, "Front UFC", "FRONT :/7 Key")
definePushButton("F_UFC_KEY_S8", 56, 3031, 300, "Front UFC", "FRONT S/8 Key")
definePushButton("F_UFC_KEY_C9", 56, 3032, 301, "Front UFC", "FRONT C/9 Key")
definePushButton("F_UFC_KEY__0", 56, 3036, 305, "Front UFC", "FRONT -/0 Key")

Open beta
F_15:definePushButton("F_UFC_KEY_7", 56, 3030, 299, "Front UFC", "FRONT :/7 Key")
F_15:definePushButton("F_UFC_KEY_S8", 56, 3031, 300, "Front UFC", "FRONT S/8 Key")
F_15:definePushButton("F_UFC_KEY_C9", 56, 3032, 301, "Front UFC", "FRONT C/9 Key")
F_15:definePushButton("F_UFC_KEY_0", 56, 3036, 305, "Front UFC", "FRONT -/0 Key")

The original key naming was F_UFC_KEY_ then the function, like S8.  I presume since the 7 is :/7 and 0 is -/0 the : and - were changed to _ resulting in a double __.

This makes the beta incompatible with code using the release version to change a number into a key name:
        ufc_key_names = {
            "1": "F_UFC_KEY_A",
            "2": "F_UFC_KEY_N",
            "3": "F_UFC_KEY_B",
            "4": "F_UFC_KEY_W",
            "5": "F_UFC_KEY_M",
            "6": "F_UFC_KEY_E",
            "7": "F_UFC_KEY__",
            "8": "F_UFC_KEY_S",
            "9": "F_UFC_KEY_C",
            "0": "F_UFC_KEY__",
        }

**Expected behavior**
If this change was not intended, it would be better to maintain the previous naming and compatibility between versions.

**Comment by charliefoxtwo** [comment]
This change was intentional. A few months ago we added some tests to ensure key names were kept consistent, and renamed those which broke our naming rules. These rules include mandating only alphanumeric characters, all letters must be uppercase, and no consecutive underscores. As there hasn't been a stable DCS release in a while (and as there likely never will be again, given they're supposedly [moving to unified releases this month](https://www.digitalcombatsimulator.com/en/news/newsletters/aafb5eb2c13e2529fae26bf92990ba23/)), dcs-bios has not seen a "stable" release in a while.
