### ISSUE TITLE
F16 ANTI_SKID_SW will not set proper position

### ISSUE THREAD

**Issue by karpiyon** [DCS-Skunkworks/dcs-bios#924]
### Version

- [X] I am using the latest version

### Aircraft

F-16

### Control

ANTI_SKID_SW

### Description

Hi,
I think there is a bug with the F-16 ANTI_SKID_SW command.
I tried both my C# code and bort and they both behave the same.
The states for the switch should be 0,1,2 yet it does not move directly to those states.

### Steps to reproduce

Load the F-16 and try to 'press' this swtich

### Screenshots

![Uploading image.png…]()

**Comment by charliefoxtwo** [comment]
Hm... this was definitely fixed in #490, but maybe ED broke something again.

I did just test and _almost_ everything works - the only issue I have is moving from state 2 to 1. Everything else seems to work as expected for me, so if you aren't at least getting that behavior then I'd suggest updating dcs-bius.

**Comment by charliefoxtwo** [comment]
Should be fixed now (for real this time). What a pain in the ass control lol

**Comment by karpiyon** [comment]
Agree…
They fix something then break if after a few ‘fixes’…
Thanks for the swift reply
